### ISSUE TITLE
[release] To do list

### ISSUE THREAD

**Issue by Chezus** [thememesquad/sempaibot#24]
TO DO:

- [ ] #10 , Reminder system: Admins / moderators should be able to remove a reminder. (Shouldn't be too hard? I wrote a comment)
- [ ] #11, Blacklist users & servers
- [ ] #17, [osu! module] Limit number of people a server can follow to prevent abuse
- [ ] #22, Admin Panel

After this is all done, we probably need to upgrade our API Key. We will need to write up an e-mail entailing how the bot works, and explain how many API calls we're going to make, and explain how we go about dealing with decay and "dead" players, so the system doesn't keep piling up more and more calls infinitely.
